//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Base.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Common {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Common() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Base.Resources.Common", typeof(Common).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brand.
        /// </summary>
        public static string Brand {
            get {
                return ResourceManager.GetString("Brand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Length.
        /// </summary>
        public static string MaxLength {
            get {
                return ResourceManager.GetString("MaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Miniature.
        /// </summary>
        public static string Miniature {
            get {
                return ResourceManager.GetString("Miniature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Miniature Collection.
        /// </summary>
        public static string MiniatureCollection {
            get {
                return ResourceManager.GetString("MiniatureCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mini Faction.
        /// </summary>
        public static string MiniFaction {
            get {
                return ResourceManager.GetString("MiniFaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mini Manufacturer.
        /// </summary>
        public static string MiniManufacturer {
            get {
                return ResourceManager.GetString("MiniManufacturer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paint Swatch.
        /// </summary>
        public static string MiniPaintSwatch {
            get {
                return ResourceManager.GetString("MiniPaintSwatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mini Properties.
        /// </summary>
        public static string MiniProperties {
            get {
                return ResourceManager.GetString("MiniProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mini State.
        /// </summary>
        public static string MiniState {
            get {
                return ResourceManager.GetString("MiniState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paints.
        /// </summary>
        public static string Paint {
            get {
                return ResourceManager.GetString("Paint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paint Series.
        /// </summary>
        public static string PaintLine {
            get {
                return ResourceManager.GetString("PaintLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paint Type.
        /// </summary>
        public static string PaintType {
            get {
                return ResourceManager.GetString("PaintType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy.
        /// </summary>
        public static string Privacy {
            get {
                return ResourceManager.GetString("Privacy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Paints.
        /// </summary>
        public static string UserPaints {
            get {
                return ResourceManager.GetString("UserPaints", resourceCulture);
            }
        }
    }
}
