//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.Resources.Views.Shared {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class _Layout {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal _Layout() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("App.Resources.Views.Shared._Layout", typeof(_Layout).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin.
        /// </summary>
        public static string Admin {
            get {
                return ResourceManager.GetString("Admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brand.
        /// </summary>
        public static string Brand {
            get {
                return ResourceManager.GetString("Brand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello.
        /// </summary>
        public static string Hello {
            get {
                return ResourceManager.GetString("Hello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Miniature.
        /// </summary>
        public static string Miniature {
            get {
                return ResourceManager.GetString("Miniature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Miniature Collection.
        /// </summary>
        public static string MiniatureCollection {
            get {
                return ResourceManager.GetString("MiniatureCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Miniature Faction.
        /// </summary>
        public static string MiniFaction {
            get {
                return ResourceManager.GetString("MiniFaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Miniature Manufacturer.
        /// </summary>
        public static string MiniManufacturer {
            get {
                return ResourceManager.GetString("MiniManufacturer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paint Swatch.
        /// </summary>
        public static string MiniPaintSwatch {
            get {
                return ResourceManager.GetString("MiniPaintSwatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Miniature Properties.
        /// </summary>
        public static string MiniProperties {
            get {
                return ResourceManager.GetString("MiniProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Miniature Status.
        /// </summary>
        public static string MiniState {
            get {
                return ResourceManager.GetString("MiniState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paint.
        /// </summary>
        public static string Paint {
            get {
                return ResourceManager.GetString("Paint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paint Series.
        /// </summary>
        public static string PaintLine {
            get {
                return ResourceManager.GetString("PaintLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paint Type.
        /// </summary>
        public static string PaintType {
            get {
                return ResourceManager.GetString("PaintType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Person.
        /// </summary>
        public static string Person {
            get {
                return ResourceManager.GetString("Person", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Paints.
        /// </summary>
        public static string PersonPaints {
            get {
                return ResourceManager.GetString("PersonPaints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
    }
}
